# Generated by Django 5.0.7 on 2024-07-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_client_alter_appointment_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.lawyer'),
        ),
    ]
