# Generated by Django 5.0.7 on 2024-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment_contact_number_alter_appointment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
